"""baseline schema
Revision ID: 04ef81c26102
Revises: 
Create Date: 2025-08-26 00:57:55.208807
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '04ef81c26102'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
