name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Sanity import check
        run: python - <<'PY'
import fastapi, uvicorn, dotenv, pydantic
print("Imports OK")
PY
      - name: Uvicorn version
        run: uvicorn --version
